global:
  scrape_interval: ${PROM_SCRAPE_INTERVAL}

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'sample-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:5000']
        labels:
          app: sample-app
